# Generated by Django 5.2.9 on 2025-12-18 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Inicio"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "responsable",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["fecha_inicio"],
                "indexes": [
                    models.Index(
                        fields=["fecha_inicio"], name="control_pro_fecha_i_532397_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_project",
                    models.IntegerField(
                        db_index=True, unique=True, verbose_name="ID Proyecto"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del Proyecto",
                    ),
                ),
                (
                    "rf",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="RF"
                    ),
                ),
                (
                    "project",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Proyecto"
                    ),
                ),
                (
                    "project_leader",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Líder de Proyecto",
                    ),
                ),
                (
                    "finalizado",
                    models.CharField(
                        blank=True,
                        default="En Curso",
                        max_length=50,
                        null=True,
                        verbose_name="Finalizado",
                    ),
                ),
                (
                    "percent_complete",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="% Complete",
                    ),
                ),
                (
                    "baseline_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Baseline Start"
                    ),
                ),
                (
                    "baseline_finish",
                    models.DateField(
                        blank=True, null=True, verbose_name="Baseline Finish"
                    ),
                ),
                (
                    "start",
                    models.DateField(blank=True, null=True, verbose_name="Start"),
                ),
                (
                    "finish",
                    models.DateField(blank=True, null=True, verbose_name="Finish"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "baseline_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Baseline Cost",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Budget",
                    ),
                ),
                (
                    "computo",
                    models.TextField(blank=True, null=True, verbose_name="Cómputo"),
                ),
                (
                    "ntp",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="NTP",
                    ),
                ),
                (
                    "scan",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="SCAN",
                    ),
                ),
                (
                    "resuelve_por_nombre",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="Resuelve por Nombre",
                    ),
                ),
                (
                    "antivirus",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="Antivirus",
                    ),
                ),
                (
                    "config_backup",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="Config Backup",
                    ),
                ),
                (
                    "monitoreo_nagios",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="Monitoreo Nagios",
                    ),
                ),
                (
                    "monitoreo_elastic",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="Monitoreo Elastic",
                    ),
                ),
                (
                    "ucmdb",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="UCMDB",
                    ),
                ),
                (
                    "conectividad_awx",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="Conectividad AWX 172.18.90.250 (SOLO UNIX)",
                    ),
                ),
                (
                    "cambio_paso_operacion_ola",
                    models.CharField(
                        blank=True,
                        default="Pendiente",
                        max_length=100,
                        null=True,
                        verbose_name="Cambio Paso Operación (OLA)",
                    ),
                ),
                (
                    "base_de_datos",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Base de Datos",
                    ),
                ),
                (
                    "balanceo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Balanceo"
                    ),
                ),
                (
                    "backup",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Backup"
                    ),
                ),
                (
                    "check_av",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Check AV"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-start", "project_name"],
                "indexes": [
                    models.Index(
                        fields=["id_project"], name="control_pro_id_proj_a3fd0d_idx"
                    ),
                    models.Index(
                        fields=["finalizado"], name="control_pro_finaliz_8d0ebd_idx"
                    ),
                    models.Index(fields=["start"], name="control_pro_start_b0d51d_idx"),
                ],
            },
        ),
    ]
