# Generated by Django 5.2.9 on 2025-12-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="cantidad_maquinas",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CANTIDAD MAQUINAS"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="cod_serv_hostname",
            field=models.TextField(
                blank=True, null=True, verbose_name="COD SERV_HOSTNAME"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="comunidad_snmp",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="COMUNIDAD SNMP"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="contacto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="CONTACTO"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="dominio",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="DOMINIO"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="fgn_172_22_16_93",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="FGN 172.22.16.93"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="observaciones",
            field=models.TextField(blank=True, null=True, verbose_name="OBSERVACIONES"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="plataforma",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PLATAFORMA"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="plataforma_backup",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PLATAFORMA BACKUP"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="proveedor",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="PROVEEDOR"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="rt",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="RT"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="servicio",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SERVICIO"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="so",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SO"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="windows_licencia_activada",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="WINDOWS LICENCIA ACTIVADA",
            ),
        ),
    ]
