# Generated by Django 5.2.9 on 2025-12-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0002_proyecto_cantidad_maquinas_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProyectoFase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("DESPLIEGUE", "Despliegue"),
                            ("ENTREGADO", "Entregado a Usuario"),
                            ("OPERACION", "Paso a Operación"),
                        ],
                        help_text="La fase en la que entró el proyecto en la fecha indicada.",
                        max_length=20,
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha en la que el proyecto entró en esta fase."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fases",
                        to="control_proyectos.proyecto",
                    ),
                ),
            ],
            options={
                "db_table": "control_proyectos_proyecto_fase",
                "ordering": ["fecha"],
                "unique_together": {("proyecto", "fecha", "fase")},
            },
        ),
    ]
