# Generated by Django 5.2.9 on 2025-12-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0003_proyectofase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proyecto",
            options={
                "ordering": ["-start", "project"],
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
            },
        ),
        migrations.RemoveIndex(
            model_name="proyecto",
            name="control_pro_finaliz_8d0ebd_idx",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="baseline_cost",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="baseline_finish",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="baseline_start",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="budget",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="finalizado",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="project_name",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                blank=True,
                default="En Curso",
                max_length=50,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AddIndex(
            model_name="proyecto",
            index=models.Index(fields=["estado"], name="control_pro_estado_abcb4a_idx"),
        ),
    ]
