# Generated by Django 5.2.9 on 2026-01-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0004_alter_proyecto_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                blank=True,
                default="Despliegue",
                max_length=50,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="proyectofase",
            name="fase",
            field=models.CharField(
                choices=[
                    ("DESPLIEGUE", "Despliegue"),
                    ("ENTREGADO", "Entregado a Usuario"),
                    ("OPERACION", "Paso a Operación"),
                    ("CIERRE", "Cierre"),
                ],
                help_text="La fase en la que entró el proyecto en la fecha indicada.",
                max_length=20,
            ),
        ),
    ]
