# Generated by Django 5.2.9 on 2026-02-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0005_alter_proyecto_estado_alter_proyectofase_fase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Cargo"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Área"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, null=True, verbose_name="Notas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["nombre"],
            },
        ),
    ]
