# Generated by Django 5.2.9 on 2026-02-26 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0006_contacto"),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name="proyecto",
        #    name="contacto",
        #),
        migrations.AddField(
            model_name="contacto",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contactos",
                to="control_proyectos.proyecto",
                verbose_name="Proyecto Asociado",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="contacto_info",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Información de Contacto (Texto)",
            ),
        ),
    ]
