# Generated by Django 5.2.9 on 2026-02-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "control_proyectos",
            "0007_remove_proyecto_contacto_contacto_proyecto_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="contacto",
        ),
    ]
