# Generated by Django 5.2.9 on 2026-03-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0008_remove_proyecto_contacto"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="contacto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_principales",
                to="control_proyectos.contacto",
                verbose_name="Contacto Principal",
            ),
        ),
    ]
