# Generated by Django 5.2.9 on 2026-03-12 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0009_remove_proyecto_contacto_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlProyectosInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Ubicación"
                    ),
                ),
                (
                    "ot",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="OT"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Código"
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Hostname"
                    ),
                ),
                (
                    "cpu",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="CPU"
                    ),
                ),
                (
                    "ram",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="RAM"
                    ),
                ),
                (
                    "disco_so",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Disco SO"
                    ),
                ),
                (
                    "disco_pag",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Disco Paginación",
                    ),
                ),
                (
                    "disco_data",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Disco Data"
                    ),
                ),
                (
                    "ip_gestion",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="IP Gestión"
                    ),
                ),
                (
                    "ip_servicios",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="IP Servicios",
                    ),
                ),
                (
                    "ip_produccion",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="IP Producción",
                    ),
                ),
                (
                    "ip_adicional_1",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="IP Adicional 1",
                    ),
                ),
                (
                    "ip_adicional_2",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="IP Adicional 2",
                    ),
                ),
                (
                    "sistema_operativo",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sistema Operativo",
                    ),
                ),
                (
                    "tipo_equipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Maquina Virtual", "Maquina Virtual"),
                            ("Maquina Fisica", "Maquina Fisica"),
                            ("Storage", "Storage"),
                            ("Switch", "Switch"),
                            ("Enclosure", "Enclosure"),
                            ("Router", "Router"),
                            ("Firewall", "Firewall"),
                            ("WAF", "WAF"),
                            ("Balanceador", "Balanceador"),
                            ("Appliance Virtual", "Appliance Virtual"),
                            ("Appliance Fisico", "Appliance Fisico"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Tipo de Equipo",
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Referencia"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario_equipos",
                        to="control_proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventario de Equipo",
                "verbose_name_plural": "Inventario de Equipos",
                "db_table": "control_proyectos_inventario",
                "ordering": ["hostname", "tipo_equipo"],
                "indexes": [
                    models.Index(
                        fields=["proyecto", "tipo_equipo"],
                        name="control_pro_proyect_3da62f_idx",
                    ),
                    models.Index(
                        fields=["hostname"], name="control_pro_hostnam_a72f6c_idx"
                    ),
                    models.Index(
                        fields=["codigo"], name="control_pro_codigo_2e5880_idx"
                    ),
                ],
            },
        ),
    ]
