# Generated by Django 5.2.9 on 2026-04-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("control_proyectos", "0010_remove_proyecto_contacto_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contacto",
            name="proyecto",
        ),
    ]
